### ISSUE TITLE
Environment definition file

### ISSUE THREAD

**Issue by johnyaku** [BayraktarLab/CountCorrect#1]
Hi Alexander.
Read the paper and very keen to apply your methods to our NanoString data.
But struggling to build a working environment.
After filling in missing dependencies etc I can now run count correct on the CPU, but not on the GPU yet.

Can you please provide an environment definition file for your conda environment (either here or in the repo)?
`conda env export --no-build -f  environment.yml`
Then I can hopefully recreate it with ...
`conda env create -f environment.yml`
I might ask for the build numbers too if I still can't get it going!

Happy to share my current environment, but might be easiest to just try to duplicate yours.
Also, which platform are you working on (Windows/Mac/Linux)?

Many thanks,
John

**Comment by AlexanderAivazidis** [comment]
Hi John,

sure I will put this together. In the meantime can I check did you follow these instructions on the main repo page?

![image](https://user-images.githubusercontent.com/46488185/127005985-f4857486-21c4-4972-8d91-0a70c7dc506c.png)
 
This should work too. But an environment.yml could indeed be even more straightforward....

Best wishes,

Alexander

**Comment by AlexanderAivazidis** [comment]
Ok I have now added an environment.yml file to the repository and updated the readme too, with instructions for how to use it. Let me know how that goes!

**Comment by AlexanderAivazidis** [comment]
And to answer the other part of your question: I am working on Linux.

**Comment by johnyaku** [comment]
Thanks Alexander, that is very helpful.
Yes, I did follow the readme instructions initially, but there were a few more dependencies that still needed to be added, such as diffxpy and some compiler libraries.
I've just created a pull request that includes a (hopefully) minimal set of dependency requirements that will (hopefully) work across platforms. I suspect that there are still one or two things missing, so please let me know if you notice anything.
For simplicity of maintenance going forward, it might be worth constraining the versions of these dependencies so that future updates don't break future attempts to create this environment. The versions in the environment.yml that you provided above could guide those constraints.
Thanks again! John
